### ISSUE TITLE
mac下安装：--kubernetes-version 未生效

### ISSUE THREAD

**Issue by Macolm6** [yuyicai/kubei#3]
安装命令：./kubei init -p root -m 192.168.1.10 --kubernetes-version 1.17.13 --image-repository registry.aliyuncs.com/google_containers  --container-engine-version 18.09.9
安装成功是最新的版本
![Snipaste_2020-10-17_21-09-26](https://user-images.githubusercontent.com/56667336/96337956-52444000-10bd-11eb-9472-c3ce47acd197.jpg)

**Comment by yuyicai** [comment]
> 安装命令：./kubei init -p root -m 192.168.1.10 --kubernetes-version 1.17.13 --image-repository registry.aliyuncs.com/google_containers  --container-engine-version 18.09.9
> 安装成功是最新的版本
> ![Snipaste_2020-10-17_21-09-26](https://user-images.githubusercontent.com/56667336/96337956-52444000-10bd-11eb-9472-c3ce47acd197.jpg)
> 

你安装k8s的系统是CentOS还是Ubuntu？具体日志可以在后面加-v 8加大日志级别查看，即`kubei init xxx -v8`  
来另外现在比较建议使用离线模式。

**Comment by Macolm6** [comment]
Centos
![image](https://user-images.githubusercontent.com/56667336/96339343-c1726200-10c6-11eb-8bef-c1efb1f410a6.png)

我试一下离线模式

会支持更多网络插件么？比如：cilium，kube-ovn等

**Comment by yuyicai** [comment]
后续考虑支持calico。cilium和kube-ovn就暂时不考虑了，手头事情比较多（其实是懒），不知道什么时候才能做😂   
后续考虑加手动部署网络插件选项吧（部署时可选择不添加网络插件，部署完成后自己kubectl apply一个）

**Comment by yuyicai** [comment]
> Centos
> ![image](https://user-images.githubusercontent.com/56667336/96339343-c1726200-10c6-11eb-8bef-c1efb1f410a6.png)
> 
> 我试一下离线模式
> 
> 会支持更多网络插件么？比如：cilium，kube-ovn等

看日志确实是版本参数没生效，但我手头没有mac，尴尬😂😂😂

**Comment by Macolm6** [comment]
> 后续考虑支持calico。cilium和kube-ovn就暂时不考虑了，手头事情比较多（其实是懒），不知道什么时候才能做😂
> 后续考虑加手动部署网络插件选项吧（部署时可选择不添加网络插件，部署完成后自己kubectl apply一个）

好的，谢谢，这样更灵活

**Comment by Macolm6** [comment]
> > Centos
> > ![image](https://user-images.githubusercontent.com/56667336/96339343-c1726200-10c6-11eb-8bef-c1efb1f410a6.png)
> > 我试一下离线模式
> > 会支持更多网络插件么？比如：cilium，kube-ovn等
> 
> 看日志确实是版本参数没生效，但我手头没有mac，尴尬😂😂😂

没关系的，安装最新版本也可以，我本地测试而已

或者你告诉我怎么调试，我可以抽空试试，或者你改了，我帮你测试

**Comment by yuyicai** [comment]
> > > Centos
> > > ![image](https://user-images.githubusercontent.com/56667336/96339343-c1726200-10c6-11eb-8bef-c1efb1f410a6.png)
> > > 我试一下离线模式
> > > 会支持更多网络插件么？比如：cilium，kube-ovn等
> > 
> > 看日志确实是版本参数没生效，但我手头没有mac，尴尬😂😂😂
> 
> 没关系的，安装最新版本也可以，我本地测试而已
> 
> 或者你告诉我怎么调试，我可以抽空试试，或者你改了，我帮你测试

感谢，我改天看看😄

**Comment by yuyicai** [comment]
> > > Centos
> > > ![image](https://user-images.githubusercontent.com/56667336/96339343-c1726200-10c6-11eb-8bef-c1efb1f410a6.png)
> > > 我试一下离线模式
> > > 会支持更多网络插件么？比如：cilium，kube-ovn等
> > 
> > 
> > 看日志确实是版本参数没生效，但我手头没有mac，尴尬😂😂😂
> 
> 没关系的，安装最新版本也可以，我本地测试而已
> 
> 或者你告诉我怎么调试，我可以抽空试试，或者你改了，我帮你测试

已经修复  
https://github.com/yuyicai/kubei/releases/tag/v0.6.1  
```
./kubei init -m 10.3.0.21 -k ~/.ssh/k8s.key --image-repository registry.aliyuncs.com/k8sxio --kubernetes-version 1.17.13 --container-engine-version 19.03.9 -v8
```

![image](https://user-images.githubusercontent.com/13033733/97178828-0129ff80-17d3-11eb-941b-1ec7f63e7dbf.png)
![image](https://user-images.githubusercontent.com/13033733/97178870-130ba280-17d3-11eb-9456-0bbb60fcc994.png)
